import {
  Refresh,
  Minus,
  Close,
  ArrowLeft,
  ArrowRight,
  CaretRight,
  CaretBottom,
  CaretTop,
  Upload,
  ArrowDown,
  QuestionFilled,
  Edit,
  UserFilled,
  EditPen,
  Search,
  Connection,
  Files,
  Notification,
  Share,
  CollectionTag,
  Reading,
  ChatLineRound,
  Plus,
  Delete,
  More,
  Filter,
  MoreFilled,
  InfoFilled,
  Document,
  Loading,
  RefreshRight,
  RefreshLeft,
  Setting,
  HelpFilled,
  User,
  Notebook,
  View,
  Warning,
  ArrowRightBold,
  CaretLeft,
  Paperclip,
  Cpu,
  CloseBold,
  Select,
  Menu
} from "@element-plus/icons-vue";

export const ICON_MAP = {
  refresh: Refresh,
  minus: Minus,
  close: Close,
  arrowRight: ArrowRight,
  caretRight: CaretRight,
  upload: Upload,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  questionFilled: QuestionFilled,
  edit: Edit,
  userFilled: UserFilled,
  editPen: EditPen,
  search: Search,
  connection: Connection,
  files: Files,
  notification: Notification,
  share: Share,
  collectionTag: CollectionTag,
  reading: Reading,
  chatLineRound: ChatLineRound,
  plus: Plus,
  delete: Delete,
  caretBottom: CaretBottom,
  more: More,
  filter: Filter,
  moreFilled: MoreFilled,
  infoFilled: InfoFilled,
  document: Document,
  loading: Loading,
  refreshRight: RefreshRight,
  refreshLeft: RefreshLeft,
  setting: Setting,
  caretTop: CaretTop,
  helpFilled: HelpFilled,
  user: User,
  notebook: Notebook,
  view: View,
  warning: Warning,
  arrowRightBold: ArrowRightBold,
  caretLeft: CaretLeft,
  paperclip: Paperclip,
  cpu: Cpu,
  closeBold: CloseBold,
  select: Select,
  menu: Menu
} as const;

export type IconKey = keyof typeof ICON_MAP;
